/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_1a_Z.h"
#include "Pin_1a_Z_aliases.h"
#include "Pin_2a_Z.h"
#include "Pin_2a_Z_aliases.h"
#include "Pin_1b_Z.h"
#include "Pin_1b_Z_aliases.h"
#include "Pin_2b_Z.h"
#include "Pin_2b_Z_aliases.h"
#include "Z_interrupt.h"
#include "Z_interrupt_aliases.h"
#include "interrupt_Z.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "LED_Red.h"
#include "LED_Red_aliases.h"
#include "LED_Green.h"
#include "LED_Green_aliases.h"
#include "LED_Blue.h"
#include "LED_Blue_aliases.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "S_interrupt.h"
#include "S_interrupt_aliases.h"
#include "interrupt_S.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

