/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_1a_X.h"
#include "Pin_1a_X_aliases.h"
#include "Pin_2a_X.h"
#include "Pin_2a_X_aliases.h"
#include "Pin_1b_X.h"
#include "Pin_1b_X_aliases.h"
#include "Pin_2b_X.h"
#include "Pin_2b_X_aliases.h"
#include "Pin_1a_Y.h"
#include "Pin_1a_Y_aliases.h"
#include "Pin_2a_Y.h"
#include "Pin_2a_Y_aliases.h"
#include "Pin_1b_Y.h"
#include "Pin_1b_Y_aliases.h"
#include "Pin_2b_Y.h"
#include "Pin_2b_Y_aliases.h"
#include "X_interrupt.h"
#include "X_interrupt_aliases.h"
#include "Y_interrupt.h"
#include "Y_interrupt_aliases.h"
#include "interrupt_X.h"
#include "interrupt_Y.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "LED_Red.h"
#include "LED_Red_aliases.h"
#include "LED_Green.h"
#include "LED_Green_aliases.h"
#include "LED_Blue.h"
#include "LED_Blue_aliases.h"
#include "SW2.h"
#include "SW2_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_SMS.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

