/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "PIR_Trig.h"
#include "PIR_Trig_aliases.h"
#include "DistTimer.h"
#include "DistEcho.h"
#include "DistEcho_aliases.h"
#include "DistTimerInt.h"
#include "DistReset.h"
#include "DistReset_aliases.h"
#include "DistTrigger.h"
#include "DistTrigger_aliases.h"
#include "LumenCom.h"
#include "LumenCom_I2C.h"
#include "LumenCom_PINS.h"
#include "LumenCom_I2C_PVT.h"
#include "LumenCom_PVT.h"
#include "LumenCom_BOOT.h"
#include "MetronomeISR.h"
#include "metronome_clock.h"
#include "MetronomeTimer.h"
#include "GreenPWM.h"
#include "GreenPin.h"
#include "GreenPin_aliases.h"
#include "RedPWM.h"
#include "RedPin.h"
#include "RedPin_aliases.h"
#include "BluePWM.h"
#include "BluePin.h"
#include "BluePin_aliases.h"
#include "I2CS.h"
#include "I2CS_I2C.h"
#include "I2CS_PINS.h"
#include "I2CS_I2C_PVT.h"
#include "I2CS_PVT.h"
#include "I2CS_BOOT.h"
#include "DEBUG.h"
#include "DEBUG_PVT.h"
#include "DistInterruptPin.h"
#include "DistInterruptPin_aliases.h"
#include "LumenCom_SCBCLK.h"
#include "LumenCom_sda.h"
#include "LumenCom_sda_aliases.h"
#include "LumenCom_scl.h"
#include "LumenCom_scl_aliases.h"
#include "LumenCom_SCB_IRQ.h"
#include "I2CS_SCBCLK.h"
#include "I2CS_sda.h"
#include "I2CS_sda_aliases.h"
#include "I2CS_scl.h"
#include "I2CS_scl_aliases.h"
#include "I2CS_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

